[config]
model="gpt-4o-mini"
model_turbo="gpt-4o-mini"
fallback_models=["gpt-4o-mini"]

[github_action_config]
auto_review = true
auto_describe = false
auto_improve = true

[pr_description]
extra_instructions="Answer in Japanese."

[pr_reviewer]
num_code_suggestions=5

[pr_code_suggestions]
num_code_suggestions=5
num_code_suggestions_per_chunk=5
