on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.actor == '75py' && github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read review guidelines
        id: read_guidelines
        run: |
          REVIEW_GUIDELINES=$(cat review_guidelines.md)
          echo "REVIEW_GUIDELINES<<EOF" >> $GITHUB_ENV
          echo "$REVIEW_GUIDELINES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: |
            Please use Japanese. 
            ${{ env.REVIEW_GUIDELINES }}
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: |
            Please use Japanese. 
            ${{ env.REVIEW_GUIDELINES }}
